name: RFC Pull Request

on: pull_request

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const RFC_CAT_ID = 'DIC_kwDOHwUU6s4CQkn_'
            const files_url = context.payload.pull_request.url + '/files'
            const diff = await github.request(files_url)
            const addedFiles = diff.data.filter(i => i.status === 'added')
            const rfcFile = addedFiles.find(i => i.filename.startsWith('rfcs/') && i.filename.endsWith('.md'))

            if (!rfcFile) {
              console.log('No RFC file found. Skipped.')
              return
            }

            console.log('RFC file found ' + renderedUrl)

            const repoUrl = context.payload.pull_request.base.repo.html_url
            const renderedUrl = context.payload.pull_request.head.repo.html_url + '/blob/' + context.payload.pull_request.head.ref + '/' + rfcFile.filename
            
            const discussionBody = [
               `[Rendered RFC](${renderedUrl})`,
               '',
               `[Pull Request](${context.payload.pull_request.html_url})`
            ].join('\\n')
            const query = `mutation {
              createDiscussion(input: { repositoryId: "${context.payload.pull_request.base.repo.node_id}", categoryId: "${RFC_CAT_ID}", body: "${discussionBody}", title: "${context.payload.pull_request.title}"}) {
                discussion {
                  url
                }
              }
            }`
            const result = await github.graphql(query)
            const discussionUrl = result.createDiscussion.discussion.url

            console.log('Discussion created ' + discussionUrl)

            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['rfc: proposed']
            })

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: [
                'This is an RFC pull request.',
                '',
                `[Rendered RFC](${renderedUrl})`,
                '',
                `[Discussion Thread](${discussionUrl})`,
                '',
                '> **Note**',
                '> **Important: Do NOT comment on this PR. Please use the discussion thread linked above to provide feedback, as it provides branched discussions that are easier to follow. This also makes the edit history of the PR clearer.**'
              ].join('\n')
            })

# To get category ID, execute following GraphQL in https://docs.github.com/en/graphql/overview/explorer
# query {
#   repository(owner: "vitejs", name: "vite") {
#     discussionCategories(first: 10) {
#       edges {
#         node {
#           name
#           id
#         }
#       }
#     }
#   }
# }
